---
cortex_project_root: "{{ role_path }}/../../.."
endpoint_coordinator_url: ""
endpoint_wifi_ssid: ""
endpoint_wifi_password: ""
endpoint_raspotify_version: 0.48.2~librespot.v0.8.0-9c7d756
endpoint_raspotify_checksum: 7f2c232af89834608bc393f6f9295a22a2659fe938f65c108b78a70c8b539733
endpoint_media_packages:
  - gstreamer1.0-libav
  - gstreamer1.0-plugins-bad
  - gstreamer1.0-plugins-base
  - gstreamer1.0-plugins-good
  - gstreamer1.0-pulseaudio
  - gstreamer1.0-x
  - netcat-openbsd
  - uxplay
