[Unit]
Wants=lightdm.service
After=lightdm.service
OnFailure=
StartLimitIntervalSec=0

[Service]
User=cortex-endpoint
Group=cortex-endpoint
PrivateUsers=false
ProtectHome=read-only
ExecStart=
ExecStart=/usr/local/bin/cortex-raspotify
ExecStopPost=-/usr/local/bin/cortex-playback-event unavailable
Restart=on-failure
RestartSec=5s
