LIBRESPOT_NAME="Cortex Home"
LIBRESPOT_BACKEND="pulseaudio"
LIBRESPOT_DEVICE_TYPE="avr"
LIBRESPOT_DISABLE_AUDIO_CACHE=
LIBRESPOT_DISABLE_CREDENTIAL_CACHE=
LIBRESPOT_ENABLE_VOLUME_NORMALISATION=
LIBRESPOT_QUIET=
